version: 2.1
orbs:
  architect: giantswarm/architect@6.13.0

workflows:
  build:
    jobs:
    - architect/go-build:
        name: go-build-klaus
        binary: klaus
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build-klaus
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main

    - architect/push-to-registries:
        context: architect
        name: push-to-registries-debian
        image: giantswarm/klaus-debian
        dockerfile: ./Dockerfile.debian
        requires:
        - go-build-klaus
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main

    - architect/push-to-app-catalog:
        executor: app-build-suite
        context: architect
        name: push-klaus-to-giantswarm-app-catalog
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: klaus
        requires:
        - push-to-registries
        - push-to-registries-debian
        persist_chart_archive: true
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main

    - architect/run-tests-with-ats:
        name: execute chart tests
        filters:
          branches:
            ignore:
            - main
        requires:
        - push-klaus-to-giantswarm-app-catalog
