version: 2.1
orbs:
  architect: giantswarm/architect@6.14.0

workflows:
  build:
    jobs:
    - architect/go-build:
        name: go-build-klaus
        binary: klaus
        filters:
          tags:
            only: /^v.*/

    # Branch builds: amd64 only for faster PR feedback
    - architect/push-to-registries-multiarch:
        context: architect
        name: push-to-registries
        platforms: "linux/amd64"
        resource_class: medium
        annotations: |
          manifest:io.giantswarm.klaus.type=toolchain
          manifest:io.giantswarm.klaus.name=klaus
          manifest:io.giantswarm.klaus.version=${DOCKER_IMAGE_TAG}
        requires:
        - go-build-klaus
        filters:
          branches:
            ignore:
            - main

    - architect/push-to-registries-multiarch:
        context: architect
        name: push-to-registries-debian
        image: giantswarm/klaus-debian
        dockerfile: ./Dockerfile.debian
        platforms: "linux/amd64"
        resource_class: medium
        annotations: |
          manifest:io.giantswarm.klaus.type=toolchain
          manifest:io.giantswarm.klaus.name=klaus
          manifest:io.giantswarm.klaus.version=${DOCKER_IMAGE_TAG}
        requires:
        - go-build-klaus
        filters:
          branches:
            ignore:
            - main

    # Branch builds: publish to klaus-toolchains namespace
    - architect/push-to-registries-multiarch:
        context: architect
        name: push-to-toolchains
        image: giantswarm/klaus-toolchains/base
        platforms: "linux/amd64"
        resource_class: medium
        annotations: |
          manifest:io.giantswarm.klaus.type=toolchain
          manifest:io.giantswarm.klaus.name=klaus
          manifest:io.giantswarm.klaus.version=${DOCKER_IMAGE_TAG}
        requires:
        - go-build-klaus
        filters:
          branches:
            ignore:
            - main

    - architect/push-to-registries-multiarch:
        context: architect
        name: push-to-toolchains-debian
        image: giantswarm/klaus-toolchains/base-debian
        dockerfile: ./Dockerfile.debian
        platforms: "linux/amd64"
        resource_class: medium
        annotations: |
          manifest:io.giantswarm.klaus.type=toolchain
          manifest:io.giantswarm.klaus.name=klaus
          manifest:io.giantswarm.klaus.version=${DOCKER_IMAGE_TAG}
        requires:
        - go-build-klaus
        filters:
          branches:
            ignore:
            - main

    # Tag builds: full multi-arch (amd64 + arm64)
    - architect/push-to-registries-multiarch:
        context: architect
        name: push-to-registries-release
        requires:
        - go-build-klaus
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

    - architect/push-to-registries-multiarch:
        context: architect
        name: push-to-registries-debian-release
        image: giantswarm/klaus-debian
        dockerfile: ./Dockerfile.debian
        requires:
        - go-build-klaus
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

    # Tag builds: publish to klaus-toolchains namespace
    - architect/push-to-registries-multiarch:
        context: architect
        name: push-to-toolchains-release
        image: giantswarm/klaus-toolchains/base
        requires:
        - go-build-klaus
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

    - architect/push-to-registries-multiarch:
        context: architect
        name: push-to-toolchains-debian-release
        image: giantswarm/klaus-toolchains/base-debian
        dockerfile: ./Dockerfile.debian
        requires:
        - go-build-klaus
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

    - architect/push-to-app-catalog:
        executor: app-build-suite
        context: architect
        name: build-klaus-chart
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: klaus
        push_to_appcatalog: false
        push_to_oci_registry: false
        persist_chart_archive: true
        requires:
        - go-build-klaus
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main

    - architect/run-tests-with-ats:
        name: execute chart tests
        requires:
        - build-klaus-chart
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main

    # Branch: push chart after tests + amd64 images
    - architect/push-to-app-catalog:
        executor: app-build-suite
        context: architect
        name: push-klaus-to-giantswarm-app-catalog
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: klaus
        requires:
        - execute chart tests
        - push-to-registries
        - push-to-registries-debian
        - push-to-toolchains
        - push-to-toolchains-debian
        filters:
          branches:
            ignore:
            - main

    # Tag: push chart after tests + multi-arch images
    - architect/push-to-app-catalog:
        executor: app-build-suite
        context: architect
        name: push-klaus-to-giantswarm-app-catalog-release
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: klaus
        requires:
        - execute chart tests
        - push-to-registries-release
        - push-to-registries-debian-release
        - push-to-toolchains-release
        - push-to-toolchains-debian-release
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
